import type { VietnameseWord, EnglishWord, ScrambleSentence, VietnameseRhymePair, EnglishSentence, VietnameseVowelRule, PreschoolItem, PreschoolColor, PreschoolShape } from '../types.ts';
import { Difficulty } from '../types.ts';

export const VIETNAMESE_WORDS: VietnameseWord[] = [
    { "image": "☔️", "sentence": "Cơn m__", "missing": "ưa", "to_type": "ua", "answer": "mưa" },
    { "image": "🥛", "sentence": "Hộp s__", "missing": "ữa", "to_type": "ua", "answer": "sữa" },
    { "image": "🌾", "sentence": "Bông l__", "missing": "úa", "to_type": "ua", "answer": "lúa" },
    { "image": "🥥", "sentence": "Quả d__", "missing": "ừa", "to_type": "ua", "answer": "dừa" },
    { "image": "🐟", "sentence": "Con c__", "missing": "á", "to_type": "a", "answer": "cá" },
    { "image": "🐔", "sentence": "Con g__", "missing": "à", "to_type": "a", "answer": "gà" },
    { "image": "🏠", "sentence": "Ngôi nh__", "missing": "à", "to_type": "a", "answer": "nhà" },
    { "image": "📖", "sentence": "Quyển s__ch", "missing": "á", "to_type": "a", "answer": "sách" },
    { "image": "🖊️", "sentence": "Cây b__t", "missing": "ú", "to_type": "u", "answer": "bút" },
    { "image": "🌸", "sentence": "Bông h__", "missing": "oa", "to_type": "oa", "answer": "hoa" },
    { "image": "🍃", "sentence": "Chiếc l__", "missing": "á", "to_type": "a", "answer": "lá" },
    { "image": "☁️", "sentence": "Đám m__y", "missing": "â", "to_type": "a", "answer": "mây" },
    { "image": "🔥", "sentence": "Ngọn l__a", "missing": "ử", "to_type": "u", "answer": "lửa" },
    { "image": "🧂", "sentence": "Hạt m__i", "missing": "uố", "to_type": "uo", "answer": "muối" },
    { "image": "⚽️", "sentence": "Quả b__g", "missing": "ó", "to_type": "o", "answer": "bóng" },
    { "image": "☀️", "sentence": "Ông mặt tr__i", "missing": "ờ", "to_type": "o", "answer": "trời" },
    { "image": "🪑", "sentence": "Cái gh__", "missing": "ế", "to_type": "e", "answer": "ghế" },
    { "image": "🚪", "sentence": "Cái c__a", "missing": "ử", "to_type": "u", "answer": "cửa" },
    { "image": "🛏️", "sentence": "Cái gi__ng", "missing": "ườ", "to_type": "uo", "answer": "giường" },
    { "image": "⏰", "sentence": "Đồng h__", "missing": "ồ", "to_type": "o", "answer": "hồ" },
    { "image": "💡", "sentence": "Bóng đ__n", "missing": "è", "to_type": "e", "answer": "đèn" },
    { "image": "🐘", "sentence": "Con v__", "missing": "oi", "to_type": "oi", "answer": "voi" },
    { "image": "🐅", "sentence": "Con h__", "missing": "ổ", "to_type": "o", "answer": "hổ" },
    { "image": "🐒", "sentence": "Con kh__", "missing": "ỉ", "to_type": "i", "answer": "khỉ" },
    { "image": "🐍", "sentence": "Con r__n", "missing": "ắ", "to_type": "a", "answer": "rắn" },
    { "image": "🐢", "sentence": "Con r__", "missing": "ù", "to_type": "u", "answer": "rùa" },
    { "image": "🦀", "sentence": "Con c__", "missing": "ua", "to_type": "ua", "answer": "cua" },
    { "image": "🐌", "sentence": "Ốc s__n", "missing": "ê", "to_type": "e", "answer": "sên" },
    { "image": "🐝", "sentence": "Con __g", "missing": "on", "to_type": "on", "answer": "ong" },
    { "image": "🦋", "sentence": "Con b__m", "missing": "ướ", "to_type": "uo", "answer": "bướm" },
    { "image": "✏️", "sentence": "Bút ch__", "missing": "ì", "to_type": "i", "answer": "chì" },
    { "image": "📓", "sentence": "Quyển v__", "missing": "ở", "to_type": "o", "answer": "vở" },
    { "image": "📏", "sentence": "Cái th__c", "missing": "ướ", "to_type": "uo", "answer": "thước" },
    { "image": "🗑️", "sentence": "Thùng r__c", "missing": "á", "to_type": "a", "answer": "rác" },
    { "image": "🔑", "sentence": "Chìa kh__", "missing": "óa", "to_type": "oa", "answer": "khóa" },
    { "image": "🚲", "sentence": "Xe đ__p", "missing": "ạ", "to_type": "a", "answer": "đạp" },
    { "image": "🛵", "sentence": "Xe m__y", "missing": "á", "to_type": "a", "answer": "máy" },
    { "image": "✈️", "sentence": "Máy b__", "missing": "ay", "to_type": "ay", "answer": "bay" },
    { "image": "🚢", "sentence": "Tàu th__y", "missing": "ủ", "to_type": "u", "answer": "thủy" },
    { "image": "🍌", "sentence": "Quả ch__i", "missing": "uố", "to_type": "uo", "answer": "chuối" },
    { "image": "🍊", "sentence": "Quả c__m", "missing": "a", "to_type": "a", "answer": "cam" },
    { "image": "🍇", "sentence": "Chùm nh__", "missing": "o", "to_type": "o", "answer": "nho" },
    { "image": "🍉", "sentence": "Dưa h__", "missing": "ấ", "to_type": "a", "answer": "hấu" },
    { "image": "🍍", "sentence": "Quả d__a", "missing": "ứ", "to_type": "u", "answer": "dứa" },
    { "image": "🌶️", "sentence": "Quả __t", "missing": "ớ", "to_type": "o", "answer": "ớt" },
    { "image": "🌽", "sentence": "Bắp ng__", "missing": "ô", "to_type": "o", "answer": "ngô" },
    { "image": "🍚", "sentence": "Bát c__m", "missing": "ơ", "to_type": "o", "answer": "cơm" },
    { "image": "🍜", "sentence": "Bát ph__", "missing": "ở", "to_type": "o", "answer": "phở" },
    { "image": "💧", "sentence": "Giọt n__c", "missing": "ướ", "to_type": "uo", "answer": "nước" },
    { "image": "🌳", "sentence": "Cái c__y", "missing": "â", "to_type": "a", "answer": "cây" },
    { "image": "⛰️", "sentence": "Ngọn n__i", "missing": "ú", "to_type": "u", "answer": "núi" },
    { "image": "🌊", "sentence": "Bờ b__n", "missing": "iể", "to_type": "ie", "answer": "biển" },
    { "image": "🚶", "sentence": "Đi b__", "missing": "ộ", "to_type": "o", "answer": "bộ" },
    { "image": "🏃", "sentence": "Ch__y nhanh", "missing": "ạ", "to_type": "a", "answer": "chạy" },
    { "image": "🤸", "sentence": "Nhảy lò c__", "missing": "ò", "to_type": "o", "answer": "cò" },
    { "image": "😋", "sentence": "Ăn c__m", "missing": "ơ", "to_type": "o", "answer": "cơm" },
    { "image": "😴", "sentence": "Đi ng__", "missing": "ủ", "to_type": "u", "answer": "ngủ" },
    { "image": "✍️", "sentence": "Học b__i", "missing": "à", "to_type": "a", "answer": "bài" },
    { "image": "👕", "sentence": "Cái __o", "missing": "á", "to_type": "a", "answer": "áo" },
    { "image": "👖", "sentence": "Cái q__n", "missing": "uầ", "to_type": "ua", "answer": "quần" },
    { "image": "👗", "sentence": "Cái v__y", "missing": "á", "to_type": "a", "answer": "váy" },
    { "image": "🎩", "sentence": "Cái m__", "missing": "ũ", "to_type": "u", "answer": "mũ" },
    { "image": "👟", "sentence": "Đôi gi__y", "missing": "à", "to_type": "a", "answer": "giày" },
    { "image": "👀", "sentence": "Đôi m__t", "missing": "ắ", "to_type": "a", "answer": "mắt" },
    { "image": "👃", "sentence": "Cái m__i", "missing": "ũ", "to_type": "u", "answer": "mũi" },
    { "image": "👄", "sentence": "Cái m__ng", "missing": "iệ", "to_type": "ie", "answer": "miệng" },
    { "image": "👂", "sentence": "Cái t__", "missing": "ai", "to_type": "ai", "answer": "tai" },
    { "image": "💪", "sentence": "Cánh t__", "missing": "ay", "to_type": "ay", "answer": "tay" },
    { "image": "🦵", "sentence": "Cái ch__n", "missing": "â", "to_type": "a", "answer": "chân" },
    { "image": "🥕", "sentence": "Củ cà r__t", "missing": "ố", "to_type": "o", "answer": "rốt" },
    { "image": "🍅", "sentence": "Cà ch__", "missing": "ua", "to_type": "ua", "answer": "chua" },
    { "image": "🥬", "sentence": "Rau c__i", "missing": "ả", "to_type": "a", "answer": "cải" },
    { "image": "🥔", "sentence": "Khoai t__y", "missing": "â", "to_type": "a", "answer": "tây" },
    { "image": "☎️", "sentence": "Điện th__i", "missing": "oạ", "to_type": "oa", "answer": "thoại" },
    { "image": "📺", "sentence": "Ti v__", "missing": "i", "to_type": "i", "answer": "vi" },
    { "image": "📷", "sentence": "Máy __nh", "missing": "ả", "to_type": "a", "answer": "ảnh" },
    { "image": "🎈", "sentence": "Bóng b__", "missing": "ay", "to_type": "ay", "answer": "bay" },
    { "image": "🎁", "sentence": "Hộp q__", "missing": "uà", "to_type": "ua", "answer": "quà" },
    { "image": "🎨", "sentence": "Bút m__u", "missing": "à", "to_type": "a", "answer": "màu" },
    { "image": "🎲", "sentence": "Xúc x__c", "missing": "ắ", "to_type": "a", "answer": "xắc" },
    { "image": "🟥", "sentence": "Màu đ__", "missing": "ỏ", "to_type": "o", "answer": "đỏ" },
    { "image": "🟨", "sentence": "Màu v__ng", "missing": "à", "to_type": "a", "answer": "vàng" },
    { "image": "🟩", "sentence": "Màu x__nh", "missing": "a", "to_type": "a", "answer": "xanh" },
    { "image": "⬜️", "sentence": "Màu tr__ng", "missing": "ắ", "to_type": "a", "answer": "trắng" },
    { "image": "⬛️", "sentence": "Màu đ__n", "missing": "e", "to_type": "e", "answer": "đen" },
    { "image": "🐷", "sentence": "Con h__", "missing": "eo", "to_type": "eo", "answer": "heo" },
    { "image": "🦆", "sentence": "Con v__", "missing": "ịt", "to_type": "it", "answer": "vịt" },
    { "image": "🦅", "sentence": "Đại b__", "missing": "àng", "to_type": "ang", "answer": "bàng" },
    { "image": "🦉", "sentence": "Con c__", "missing": "ú", "to_type": "u", "answer": "cú" },
    { "image": "🎋", "sentence": "Cây tr__", "missing": "e", "to_type": "e", "answer": "tre" },
    { "image": "💐", "sentence": "Bó h__", "missing": "oa", "to_type": "oa", "answer": "hoa" },
    { "image": "🍄", "sentence": "Cây n__m", "missing": "ấm", "to_type": "am", "answer": "nấm" },
    { "image": "🚑", "sentence": "Xe c__u thương", "missing": "ứu", "to_type": "uu", "answer": "cứu" },
    { "image": "🚒", "sentence": "Xe c__u hỏa", "missing": "ứu", "to_type": "uu", "answer": "cứu" },
    { "image": "🚔", "sentence": "Xe c__nh sát", "missing": "ả", "to_type": "a", "answer": "cảnh" },
    { "image": "🚜", "sentence": "Máy c__y", "missing": "à", "to_type": "a", "answer": "cày" },
    { "image": "🧦", "sentence": "Đôi t__t", "missing": "ấ", "to_type": "a", "answer": "tất" },
    { "image": "🧤", "sentence": "Găng t__", "missing": "ay", "to_type": "ay", "answer": "tay" },
    { "image": "🧣", "sentence": "Khăn qu__ng", "missing": "à", "to_type": "a", "answer": "quàng" },
    { "image": "👓", "sentence": "Cái k__nh", "missing": "í", "to_type": "i", "answer": "kính" },
    { "image": "☂️", "sentence": "Cái __", "missing": "ô", "to_type": "o", "answer": "ô" },
    { "image": "🥁", "sentence": "Cái tr__ng", "missing": "ố", "to_type": "o", "answer": "trống" },
    { "image": "🎸", "sentence": "Đàn ghi t__", "missing": "a", "to_type": "a", "answer": "ta" },
    { "image": "🎺", "sentence": "Cái k__n", "missing": "è", "to_type": "e", "answer": "kèn" },
    { "image": "🎻", "sentence": "Đàn v__ cầm", "missing": "ĩ", "to_type": "i", "answer": "vĩ" },
    { "image": "🧵", "sentence": "Cuộn ch__", "missing": "ỉ", "to_type": "i", "answer": "chỉ" },
    { "image": "🧷", "sentence": "Cái k__m", "missing": "i", "to_type": "i", "answer": "kim" },
    { "image": "✂️", "sentence": "Cái k__o", "missing": "é", "to_type": "e", "answer": "kéo" },
    { "image": "🔨", "sentence": "Cái b__a", "missing": "ú", "to_type": "u", "answer": "búa" },
    { "image": "🔧", "sentence": "Cái c__ lê", "missing": "ờ", "to_type": "o", "answer": "cờ" },
    { "image": "🪛", "sentence": "Tua v__t", "missing": "í", "to_type": "i", "answer": "vít" },
    { "image": "🪚", "sentence": "Cái c__a", "missing": "ư", "to_type": "u", "answer": "cưa" },
    { "image": "🪜", "sentence": "Cái th__ng", "missing": "a", "to_type": "a", "answer": "thang" },
    { "image": "🧽", "sentence": "Miếng x__p", "missing": "ố", "to_type": "o", "answer": "xốp" },
    { "image": "🪣", "sentence": "Cái x__", "missing": "ô", "to_type": "o", "answer": "xô" },
    { "image": "🧼", "sentence": "Xà ph__ng", "missing": "ò", "to_type": "o", "answer": "phòng" },
    { "image": "🪥", "sentence": "Bàn ch__i", "missing": "ả", "to_type": "a", "answer": "chải" },
    { "image": "🪒", "sentence": "Dao c__o", "missing": "ạ", "to_type": "a", "answer": "cạo" },
    { "image": "🧺", "sentence": "Cái gi__", "missing": "ỏ", "to_type": "o", "answer": "giỏ" },
    { "image": "🧻", "sentence": "Giấy v__ sinh", "missing": "ệ", "to_type": "e", "answer": "vệ" },
    { "image": "🛁", "sentence": "Bồn t__m", "missing": "ắ", "to_type": "a", "answer": "tắm" }
];

export const VIETNAMESE_SCRAMBLE_SENTENCES: ScrambleSentence[] = [
    { "sentence": "Em yêu trường em", "difficulty": Difficulty.EASY },
    { "sentence": "Mẹ là cô giáo", "difficulty": Difficulty.EASY },
    { "sentence": "Bà đang nấu cơm", "difficulty": Difficulty.EASY },
    { "sentence": "Bố đọc báo", "difficulty": Difficulty.EASY },
    { "sentence": "Hôm nay trời đẹp", "difficulty": Difficulty.EASY },
    { "sentence": "Bé thích đi học", "difficulty": Difficulty.EASY },
    { "sentence": "Em có bút mới", "difficulty": Difficulty.EASY },
    { "sentence": "Con gà gáy to", "difficulty": Difficulty.EASY },
    { "sentence": "Quả bóng màu xanh", "difficulty": Difficulty.EASY },
    { "sentence": "Cá bơi dưới nước", "difficulty": Difficulty.EASY },
    { "sentence": "Em bé đang ngủ", "difficulty": Difficulty.EASY },
    { "sentence": "Ông đang tưới cây", "difficulty": Difficulty.EASY },
    { "sentence": "Nhà em ở đây", "difficulty": Difficulty.EASY },
    { "sentence": "Bầu trời màu xanh", "difficulty": Difficulty.EASY },
    { "sentence": "Mặt trời toả nắng", "difficulty": Difficulty.EASY },
    { "sentence": "Con chó đang chạy", "difficulty": Difficulty.EASY },
    { "sentence": "Bông hoa màu đỏ", "difficulty": Difficulty.EASY },
    { "sentence": "Cái cây rất cao", "difficulty": Difficulty.EASY },
    { "sentence": "Bé đang vẽ tranh", "difficulty": Difficulty.EASY },
    { "sentence": "Em uống sữa", "difficulty": Difficulty.EASY },
    { "sentence": "Đàn chim bay cao", "difficulty": Difficulty.EASY },
    { "sentence": "Gió thổi mát quá", "difficulty": Difficulty.EASY },
    { "sentence": "Mẹ đi chợ về", "difficulty": Difficulty.EASY },
    { "sentence": "Bé chơi xếp hình", "difficulty": Difficulty.EASY },
    { "sentence": "Trăng sáng quá", "difficulty": Difficulty.EASY },
    { "sentence": "Mưa rơi tí tách", "difficulty": Difficulty.EASY },
    { "sentence": "Bé ăn cơm ngon", "difficulty": Difficulty.EASY },
    { "sentence": "Bố đi làm về", "difficulty": Difficulty.EASY },
    { "sentence": "Con mèo rửa mặt", "difficulty": Difficulty.EASY },
    { "sentence": "Cây ra hoa đẹp", "difficulty": Difficulty.EASY },
    { "sentence": "Bé tập đi xe", "difficulty": Difficulty.EASY },
    { "sentence": "Chị chải tóc dài", "difficulty": Difficulty.EASY },
    { "sentence": "Em rửa tay sạch", "difficulty": Difficulty.EASY },
    { "sentence": "Bé nghe lời bà", "difficulty": Difficulty.EASY },
    { "sentence": "Trường em rất đẹp", "difficulty": Difficulty.EASY },
    { "sentence": "Cờ đỏ sao vàng", "difficulty": Difficulty.EASY },
    { "sentence": "Bé ngoan học giỏi", "difficulty": Difficulty.EASY },
    { "sentence": "Đường phố đông vui", "difficulty": Difficulty.EASY },
    { "sentence": "Em yêu hòa bình", "difficulty": Difficulty.EASY },
    { "sentence": "Cây xanh tỏa bóng", "difficulty": Difficulty.EASY },
    { "sentence": "Con mèo bắt chuột", "difficulty": Difficulty.HARD },
    { "sentence": "Chú chó sủa gâu gâu", "difficulty": Difficulty.HARD },
    { "sentence": "Bông hoa này rất đẹp", "difficulty": Difficulty.HARD },
    { "sentence": "Bầu trời hôm nay trong xanh", "difficulty": Difficulty.HARD },
    { "sentence": "Em thích ăn kem sô cô la", "difficulty": Difficulty.HARD },
    { "sentence": "Gia đình em có bốn người", "difficulty": Difficulty.HARD },
    { "sentence": "Chúng em đang chăm chỉ học bài", "difficulty": Difficulty.HARD },
    { "sentence": "Mùa hè có hoa phượng nở đỏ rực", "difficulty": Difficulty.HARD },
    { "sentence": "Bố em là một kỹ sư giỏi", "difficulty": Difficulty.HARD },
    { "sentence": "Mẹ em nấu những món ăn rất ngon", "difficulty": Difficulty.HARD },
    { "sentence": "Ngoài sân các bạn đang chơi đá cầu", "difficulty": Difficulty.HARD },
    { "sentence": "Bà thường kể cho em nghe chuyện cổ tích", "difficulty": Difficulty.HARD },
    { "sentence": "Em rất thích đọc sách và truyện tranh", "difficulty": Difficulty.HARD },
    { "sentence": "Chú bộ đội đang canh giữ biển trời", "difficulty": Difficulty.HARD },
    { "sentence": "Con chim sẻ đang hót líu lo trên cành cây", "difficulty": Difficulty.HARD },
    { "sentence": "Chiếc xe buýt đang chạy trên đường phố", "difficulty": Difficulty.HARD },
    { "sentence": "Em giúp mẹ quét nhà và rửa bát", "difficulty": Difficulty.HARD },
    { "sentence": "Ngày mai chúng em được nghỉ học", "difficulty": Difficulty.HARD },
    { "sentence": "Cô giáo đang giảng bài trên lớp", "difficulty": Difficulty.HARD },
    { "sentence": "Nước biển có vị mặn", "difficulty": Difficulty.HARD },
    { "sentence": "Dòng sông chảy hiền hòa qua cánh đồng", "difficulty": Difficulty.HARD },
    { "sentence": "Những chú trâu đang thong thả gặm cỏ", "difficulty": Difficulty.HARD },
    { "sentence": "Buổi sáng ông mặt trời thức dậy sớm", "difficulty": Difficulty.HARD },
    { "sentence": "Đêm qua trời mưa rất to", "difficulty": Difficulty.HARD },
    { "sentence": "Em mơ ước trở thành phi công", "difficulty": Difficulty.HARD },
    { "sentence": "Cánh diều bay cao trong gió chiều", "difficulty": Difficulty.HARD },
    { "sentence": "Mùa thu lá vàng rơi đầy sân", "difficulty": Difficulty.HARD },
    { "sentence": "Những bông hoa cúc nở vàng rực rỡ", "difficulty": Difficulty.HARD },
    { "sentence": "Tết đến xuân về trăm hoa đua nở", "difficulty": Difficulty.HARD },
    { "sentence": "Em rất vui khi được điểm mười", "difficulty": Difficulty.HARD },
    { "sentence": "Chúng em thi đua giữ vở sạch chữ đẹp", "difficulty": Difficulty.HARD },
    { "sentence": "Trường của em lợp ngói đỏ tươi", "difficulty": Difficulty.HARD },
    { "sentence": "Các bạn nam đang chơi đá bóng ngoài sân", "difficulty": Difficulty.HARD },
    { "sentence": "Tiếng trống trường vang lên rộn rã", "difficulty": Difficulty.HARD },
    { "sentence": "Mẹ mua cho em chiếc áo mới", "difficulty": Difficulty.HARD },
    { "sentence": "Bữa cơm gia đình thật ấm cúng", "difficulty": Difficulty.HARD },
    { "sentence": "Em hứa sẽ luôn chăm ngoan học giỏi", "difficulty": Difficulty.HARD },
    { "sentence": "Cây bàng trước sân trường tỏa bóng mát", "difficulty": Difficulty.HARD },
    { "sentence": "Những chú ong chăm chỉ đi tìm mật", "difficulty": Difficulty.HARD },
    { "sentence": "Đàn kiến nối đuôi nhau tha mồi về tổ", "difficulty": Difficulty.HARD }
];

export const VIETNAMESE_RHYMES: VietnameseRhymePair[] = [
    { "word": "nhà", "rhyme": "gà", "options": ["cá", "gà", "mây"], "difficulty": Difficulty.EASY },
    { "word": "sách", "rhyme": "bách", "options": ["vở", "bút", "bách"], "difficulty": Difficulty.EASY },
    { "word": "sông", "rhyme": "đồng", "options": ["đồng", "núi", "biển"], "difficulty": Difficulty.EASY },
    { "word": "cây", "rhyme": "mây", "options": ["lá", "mây", "cành"], "difficulty": Difficulty.EASY },
    { "word": "bút", "rhyme": "mút", "options": ["thước", "mút", "phấn"], "difficulty": Difficulty.EASY },
    { "word": "hoa", "rhyme": "loa", "options": ["cỏ", "loa", "nụ"], "difficulty": Difficulty.EASY },
    { "word": "bàn", "rhyme": "nan", "options": ["ghế", "nan", "tủ"], "difficulty": Difficulty.EASY },
    { "word": "cơm", "rhyme": "thơm", "options": ["canh", "cá", "thơm"], "difficulty": Difficulty.EASY },
    { "word": "biển", "rhyme": "tiền", "options": ["sóng", "tiền", "cát"], "difficulty": Difficulty.EASY },
    { "word": "mưa", "rhyme": "dừa", "options": ["nắng", "gió", "dừa"], "difficulty": Difficulty.EASY },
    { "word": "bóng", "rhyme": "sóng", "options": ["gôn", "sóng", "rổ"], "difficulty": Difficulty.EASY },
    { "word": "cam", "rhyme": "tam", "options": ["táo", "tam", "lê"], "difficulty": Difficulty.EASY },
    { "word": "mũ", "rhyme": "đu đủ", "options": ["áo", "quần", "đu đủ"], "difficulty": Difficulty.EASY },
    { "word": "bão", "rhyme": "táo", "options": ["lê", "táo", "mận"], "difficulty": Difficulty.EASY },
    { "word": "mèo", "rhyme": "trèo", "options": ["chó", "lợn", "trèo"], "difficulty": Difficulty.EASY },
    { "word": "tay", "rhyme": "bay", "options": ["chân", "bay", "đầu"], "difficulty": Difficulty.EASY },
    { "word": "chân", "rhyme": "sân", "options": ["tay", "sân", "mắt"], "difficulty": Difficulty.EASY },
    { "word": "mắt", "rhyme": "cắt", "options": ["mũi", "cắt", "tai"], "difficulty": Difficulty.EASY },
    { "word": "tai", "rhyme": "vai", "options": ["tay", "vai", "chân"], "difficulty": Difficulty.EASY },
    { "word": "tóc", "rhyme": "khóc", "options": ["mắt", "khóc", "miệng"], "difficulty": Difficulty.EASY },
    { "word": "đá", "rhyme": "cá", "options": ["cỏ", "cá", "cây"], "difficulty": Difficulty.EASY },
    { "word": "cỏ", "rhyme": "thỏ", "options": ["cây", "thỏ", "hoa"], "difficulty": Difficulty.EASY },
    { "word": "lúa", "rhyme": "múa", "options": ["ngô", "múa", "khoai"], "difficulty": Difficulty.EASY },
    { "word": "ngô", "rhyme": "ô", "options": ["lúa", "ô", "sắn"], "difficulty": Difficulty.EASY },
    { "word": "chó", "rhyme": "ngó", "options": ["mèo", "ngó", "gà"], "difficulty": Difficulty.EASY },
    { "word": "yêu", "rhyme": "diều", "options": ["ghét", "thương", "diều"], "difficulty": Difficulty.HARD },
    { "word": "trường", "rhyme": "phường", "options": ["lớp", "phường", "cổng"], "difficulty": Difficulty.HARD },
    { "word": "đường", "rhyme": "sương", "options": ["sương", "phố", "vỉa hè"], "difficulty": Difficulty.HARD },
    { "word": "thương", "rhyme": "vương", "options": ["nhớ", "vương", "trông"], "difficulty": Difficulty.HARD },
    { "word": "hoàng", "rhyme": "loang", "options": ["xanh", "loang", "tím"], "difficulty": Difficulty.HARD },
    { "word": "chuyện", "rhyme": "truyện", "options": ["kể", "đọc", "truyện"], "difficulty": Difficulty.HARD },
    { "word": "ngoan", "rhyme": "hoan", "options": ["hoan", "hiền", "giỏi"], "difficulty": Difficulty.HARD },
    { "word": "xanh", "rhyme": "chanh", "options": ["đỏ", "chanh", "vàng"], "difficulty": Difficulty.HARD },
    { "word": "khỏe", "rhyme": "nhẹ", "options": ["mạnh", "yếu", "nhẹ"], "difficulty": Difficulty.HARD },
    { "word": "nghiêng", "rhyme": "chiêng", "options": ["trống", "chiêng", "thẳng"], "difficulty": Difficulty.HARD },
    { "word": "loắt choắt", "rhyme": "thoăn thoắt", "options": ["thoăn thoắt", "lớn", "bé"], "difficulty": Difficulty.HARD },
    { "word": "uyển chuyển", "rhyme": "khuyến", "options": ["cứng", "khuyến", "mềm"], "difficulty": Difficulty.HARD },
    { "word": "nghệch ngoạc", "rhyme": "loạc choạc", "options": ["đẹp", "loạc choạc", "xấu"], "difficulty": Difficulty.HARD },
    { "word": "quanh co", "rhyme": "vo", "options": ["thẳng", "vo", "dài"], "difficulty": Difficulty.HARD },
    { "word": "hươu", "rhyme": "cừu", "options": ["nai", "cừu", "bò"], "difficulty": Difficulty.HARD },
    { "word": "khuyên", "rhyme": "tuyên", "options": ["nói", "tuyên", "bảo"], "difficulty": Difficulty.HARD },
    { "word": "huyên náo", "rhyme": "táo", "options": ["yên", "táo", "lặng"], "difficulty": Difficulty.HARD },
    { "word": "lấp lánh", "rhyme": "cánh", "options": ["tối", "cánh", "sáng"], "difficulty": Difficulty.HARD },
    { "word": "rực rỡ", "rhyme": "cỡ", "options": ["xấu", "cỡ", "nhạt"], "difficulty": Difficulty.HARD },
    { "word": "mênh mông", "rhyme": "sông", "options": ["hẹp", "sông", "nhỏ"], "difficulty": Difficulty.HARD },
    { "word": "bát ngát", "rhyme": "hát", "options": ["bé", "hát", "chật"], "difficulty": Difficulty.HARD },
    { "word": "thênh thang", "rhyme": "lang", "options": ["chật", "lang", "hẹp"], "difficulty": Difficulty.HARD },
    { "word": "nhấp nhô", "rhyme": "ô", "options": ["phẳng", "ô", "lì"], "difficulty": Difficulty.HARD },
    { "word": "ngoằn ngoèo", "rhyme": "mèo", "options": ["thẳng", "mèo", "ngay"], "difficulty": Difficulty.HARD },
    { "word": "khúc khuỷu", "rhyme": "khuỷu", "options": ["thẳng", "khuỷu", "phẳng"], "difficulty": Difficulty.HARD }
];

export const VIETNAMESE_VOWEL_RULES: VietnameseVowelRule[] = [
    { "result": "ă", "guide": "a + w", "description": "Gõ 'a' và 'w' để được 'ă'" },
    { "result": "â", "guide": "a + a", "description": "Gõ 'a' và 'a' để được 'â'" },
    { "result": "đ", "guide": "d + d", "description": "Gõ 'd' và 'd' để được 'đ'" },
    { "result": "ê", "guide": "e + e", "description": "Gõ 'e' và 'e' để được 'ê'" },
    { "result": "ô", "guide": "o + o", "description": "Gõ 'o' và 'o' để được 'ô'" },
    { "result": "ơ", "guide": "o + w", "description": "Gõ 'o' và 'w' để được 'ơ'" },
    { "result": "ư", "guide": "u + w", "description": "Gõ 'u' và 'w' để được 'ư'" },
    { "result": "á", "guide": "a + s", "description": "Thêm 's' để có dấu sắc" },
    { "result": "é", "guide": "e + s", "description": "Thêm 's' để có dấu sắc" },
    { "result": "ố", "guide": "ô + s", "description": "Thêm 's' để có dấu sắc" },
    { "result": "à", "guide": "a + f", "description": "Thêm 'f' để có dấu huyền" },
    { "result": "è", "guide": "e + f", "description": "Thêm 'f' để có dấu huyền" },
    { "result": "ồ", "guide": "ô + f", "description": "Thêm 'f' để có dấu huyền" },
    { "result": "ả", "guide": "a + r", "description": "Thêm 'r' để có dấu hỏi" },
    { "result": "ẻ", "guide": "e + r", "description": "Thêm 'r' để có dấu hỏi" },
    { "result": "ổ", "guide": "ô + r", "description": "Thêm 'r' để có dấu hỏi" },
    { "result": "ã", "guide": "a + x", "description": "Thêm 'x' để có dấu ngã" },
    { "result": "ẽ", "guide": "e + x", "description": "Thêm 'x' để có dấu ngã" },
    { "result": "ỗ", "guide": "ô + x", "description": "Thêm 'x' để có dấu ngã" },
    { "result": "ạ", "guide": "a + j", "description": "Thêm 'j' để có dấu nặng" },
    { "result": "ẹ", "guide": "e + j", "description": "Thêm 'j' để có dấu nặng" },
    { "result": "ộ", "guide": "ô + j", "description": "Thêm 'j' để có dấu nặng" },
    { "result": "xóa dấu", "guide": "... + z", "description": "Thêm 'z' để xóa dấu đã gõ" }
];

export const ENGLISH_WORDS: EnglishWord[] = [
    { "image": "🍎", "word": "apple", "sentence": "an a__le", "missing": "pp", "difficulty": Difficulty.EASY },
    { "image": "⚽️", "word": "ball", "sentence": "a b__l", "missing": "al", "difficulty": Difficulty.EASY },
    { "image": "🐱", "word": "cat", "sentence": "a c__t", "missing": "a", "difficulty": Difficulty.EASY },
    { "image": "🐶", "word": "dog", "sentence": "a d__g", "missing": "o", "difficulty": Difficulty.EASY },
    { "image": "☀️", "word": "sun", "sentence": "the s__n", "missing": "u", "difficulty": Difficulty.EASY },
    { "image": "🚗", "word": "car", "sentence": "a c__r", "missing": "a", "difficulty": Difficulty.EASY },
    { "image": "📖", "word": "book", "sentence": "a b__k", "missing": "oo", "difficulty": Difficulty.EASY },
    { "image": "🖊️", "word": "pen", "sentence": "a p__n", "missing": "e", "difficulty": Difficulty.EASY },
    { "image": "🐷", "word": "pig", "sentence": "a p__g", "missing": "i", "difficulty": Difficulty.EASY },
    { "image": "👑", "word": "king", "sentence": "a k__g", "missing": "in", "difficulty": Difficulty.EASY },
    { "image": "🐟", "word": "fish", "sentence": "a f__h", "missing": "is", "difficulty": Difficulty.EASY },
    { "image": "🌳", "word": "tree", "sentence": "a t__e", "missing": "re", "difficulty": Difficulty.EASY },
    { "image": "🛏️", "word": "bed", "sentence": "a b__d", "missing": "e", "difficulty": Difficulty.EASY },
    { "image": "✋", "word": "hand", "sentence": "my h__d", "missing": "an", "difficulty": Difficulty.EASY },
    { "image": "🥛", "word": "milk", "sentence": "I drink m__k", "missing": "il", "difficulty": Difficulty.EASY },
    { "image": "🐸", "word": "frog", "sentence": "a green f__g", "missing": "ro", "difficulty": Difficulty.EASY },
    { "image": "🦆", "word": "duck", "sentence": "a yellow d__k", "missing": "uc", "difficulty": Difficulty.EASY },
    { "image": "🐜", "word": "ant", "sentence": "a small __t", "missing": "an", "difficulty": Difficulty.EASY },
    { "image": "🥚", "word": "egg", "sentence": "an e__", "missing": "gg", "difficulty": Difficulty.EASY },
    { "image": "🔟", "word": "ten", "sentence": "number t__", "missing": "en", "difficulty": Difficulty.EASY },
    { "image": "🐝", "word": "bee", "sentence": "a busy b__", "missing": "ee", "difficulty": Difficulty.EASY },
    { "image": "🧢", "word": "hat", "sentence": "a blue h__", "missing": "at", "difficulty": Difficulty.EASY },
    { "image": "🔑", "word": "key", "sentence": "a door k__", "missing": "ey", "difficulty": Difficulty.EASY },
    { "image": "🦵", "word": "leg", "sentence": "my l__", "missing": "eg", "difficulty": Difficulty.EASY },
    { "image": "👄", "word": "lip", "sentence": "red l__", "missing": "ip", "difficulty": Difficulty.EASY },
    { "image": "🗺️", "word": "map", "sentence": "a treasure m__", "missing": "ap", "difficulty": Difficulty.EASY },
    { "image": "🦊", "word": "fox", "sentence": "a clever f__", "missing": "ox", "difficulty": Difficulty.EASY },
    { "image": "📦", "word": "box", "sentence": "a big b__", "missing": "ox", "difficulty": Difficulty.EASY },
    { "image": "👦", "word": "boy", "sentence": "a little b__", "missing": "oy", "difficulty": Difficulty.EASY },
    { "image": "🧸", "word": "toy", "sentence": "a new t__", "missing": "oy", "difficulty": Difficulty.EASY },
    { "image": "🚌", "word": "bus", "sentence": "a yellow b__", "missing": "us", "difficulty": Difficulty.EASY },
    { "image": "☕", "word": "cup", "sentence": "a tea c__", "missing": "up", "difficulty": Difficulty.EASY },
    { "image": "🧢", "word": "cap", "sentence": "wear a c__", "missing": "ap", "difficulty": Difficulty.EASY },
    { "image": "🏃", "word": "run", "sentence": "I can r__", "missing": "un", "difficulty": Difficulty.EASY },
    { "image": "🛑", "word": "red", "sentence": "color r__", "missing": "ed", "difficulty": Difficulty.EASY },
    { "image": "🧍", "word": "man", "sentence": "a tall m__", "missing": "an", "difficulty": Difficulty.EASY },
    { "image": "🏠", "word": "house", "sentence": "a h__se", "missing": "ou", "difficulty": Difficulty.MEDIUM },
    { "image": "💧", "word": "water", "sentence": "some w__er", "missing": "at", "difficulty": Difficulty.MEDIUM },
    { "image": "🪑", "word": "chair", "sentence": "a ch__r", "missing": "ai", "difficulty": Difficulty.MEDIUM },
    { "image": "🍽️", "word": "table", "sentence": "a t__le", "missing": "ab", "difficulty": Difficulty.MEDIUM },
    { "image": "🍞", "word": "bread", "sentence": "a piece of b__ad", "missing": "re", "difficulty": Difficulty.MEDIUM },
    { "image": "🍓", "word": "strawberry", "sentence": "a s__berry", "missing": "traw", "difficulty": Difficulty.MEDIUM },
    { "image": "🏫", "word": "school", "sentence": "go to s__l", "missing": "choo", "difficulty": Difficulty.MEDIUM },
    { "image": "💡", "word": "light", "sentence": "turn on the l__t", "missing": "igh", "difficulty": Difficulty.MEDIUM },
    { "image": "🌙", "word": "moon", "sentence": "the m__n", "missing": "oo", "difficulty": Difficulty.MEDIUM },
    { "image": "⭐", "word": "star", "sentence": "a bright s__r", "missing": "ta", "difficulty": Difficulty.MEDIUM },
    { "image": "🐯", "word": "tiger", "sentence": "a big t__er", "missing": "ig", "difficulty": Difficulty.MEDIUM },
    { "image": "🦁", "word": "lion", "sentence": "a brave l__n", "missing": "io", "difficulty": Difficulty.MEDIUM },
    { "image": "🌸", "word": "flower", "sentence": "a beautiful fl__er", "missing": "ow", "difficulty": Difficulty.MEDIUM },
    { "image": "🚆", "word": "train", "sentence": "a long t__in", "missing": "ra", "difficulty": Difficulty.MEDIUM },
    { "image": "🐑", "word": "sheep", "sentence": "a white sh__p", "missing": "ee", "difficulty": Difficulty.MEDIUM },
    { "image": "😊", "word": "happy", "sentence": "I am h__py", "missing": "ap", "difficulty": Difficulty.MEDIUM },
    { "image": "😢", "word": "sad", "sentence": "don't be s__", "missing": "ad", "difficulty": Difficulty.MEDIUM },
    { "image": "👨‍⚕️", "word": "doctor", "sentence": "a d__tor", "missing": "oc", "difficulty": Difficulty.MEDIUM },
    { "image": "👩‍⚕️", "word": "nurse", "sentence": "a kind n__se", "missing": "ur", "difficulty": Difficulty.MEDIUM },
    { "image": "👮", "word": "police", "sentence": "a p__ice officer", "missing": "ol", "difficulty": Difficulty.MEDIUM },
    { "image": "👩‍🏫", "word": "teacher", "sentence": "my t__cher", "missing": "ea", "difficulty": Difficulty.MEDIUM },
    { "image": "🚒", "word": "fire", "sentence": "a f__e truck", "missing": "ir", "difficulty": Difficulty.MEDIUM },
    { "image": "🚌", "word": "bus", "sentence": "a school b__", "missing": "us", "difficulty": Difficulty.MEDIUM },
    { "image": "🐎", "word": "horse", "sentence": "ride a h__se", "missing": "or", "difficulty": Difficulty.MEDIUM },
    { "image": "🐦", "word": "bird", "sentence": "a little b__d", "missing": "ir", "difficulty": Difficulty.MEDIUM },
    { "image": "🐍", "word": "snake", "sentence": "a long s__ke", "missing": "na", "difficulty": Difficulty.MEDIUM },
    { "image": "🐼", "word": "panda", "sentence": "a cute p__da", "missing": "an", "difficulty": Difficulty.MEDIUM },
    { "image": "🦓", "word": "zebra", "sentence": "a striped z__ra", "missing": "eb", "difficulty": Difficulty.MEDIUM },
    { "image": "🐒", "word": "monkey", "sentence": "a funny m__key", "missing": "on", "difficulty": Difficulty.MEDIUM },
    { "image": "🐇", "word": "rabbit", "sentence": "a fast r__bit", "missing": "ab", "difficulty": Difficulty.MEDIUM },
    { "image": "🧀", "word": "cheese", "sentence": "some ch__se", "missing": "ee", "difficulty": Difficulty.MEDIUM },
    { "image": "🍕", "word": "pizza", "sentence": "yummy p__za", "missing": "iz", "difficulty": Difficulty.MEDIUM },
    { "image": "🍔", "word": "burger", "sentence": "a big b__ger", "missing": "ur", "difficulty": Difficulty.MEDIUM },
    { "image": "🐘", "word": "elephant", "sentence": "an e__ant", "missing": "leph", "difficulty": Difficulty.HARD },
    { "image": "💻", "word": "computer", "sentence": "a c__er", "missing": "omput", "difficulty": Difficulty.HARD },
    { "image": "🌎", "word": "world", "sentence": "the w__d", "missing": "orl", "difficulty": Difficulty.HARD },
    { "image": "🎸", "word": "guitar", "sentence": "play the g__r", "missing": "uita", "difficulty": Difficulty.HARD },
    { "image": "🌻", "word": "sunflower", "sentence": "a yellow s__flower", "missing": "un", "difficulty": Difficulty.HARD },
    { "image": "🦋", "word": "butterfly", "sentence": "a beautiful b__fly", "missing": "utter", "difficulty": Difficulty.HARD },
    { "image": "🌈", "word": "rainbow", "sentence": "a colorful r__bow", "missing": "ain", "difficulty": Difficulty.HARD },
    { "image": "🥒", "word": "cucumber", "sentence": "a green c__mber", "missing": "ucu", "difficulty": Difficulty.HARD },
    { "image": "🦖", "word": "dinosaur", "sentence": "a big d__saur", "missing": "ino", "difficulty": Difficulty.HARD },
    { "image": "🚁", "word": "helicopter", "sentence": "a h__copter", "missing": "eli", "difficulty": Difficulty.HARD },
    { "image": "🏥", "word": "hospital", "sentence": "go to the h__pital", "missing": "os", "difficulty": Difficulty.HARD },
    { "image": "📚", "word": "library", "sentence": "read books in the l__rary", "missing": "ib", "difficulty": Difficulty.HARD },
    { "image": "🍳", "word": "kitchen", "sentence": "cook in the k__chen", "missing": "it", "difficulty": Difficulty.HARD },
    { "image": "🛌", "word": "bedroom", "sentence": "sleep in the b__room", "missing": "ed", "difficulty": Difficulty.HARD },
    { "image": "🍊", "word": "orange", "sentence": "an __ge", "missing": "oran", "difficulty": Difficulty.HARD },
    { "image": "🍌", "word": "banana", "sentence": "a yellow b__na", "missing": "ana", "difficulty": Difficulty.HARD },
    { "image": "🥔", "word": "potato", "sentence": "a brown p__to", "missing": "ota", "difficulty": Difficulty.HARD },
    { "image": "🍅", "word": "tomato", "sentence": "a red t__to", "missing": "oma", "difficulty": Difficulty.HARD },
    { "image": "🥑", "word": "avocado", "sentence": "green a__cado", "missing": "vo", "difficulty": Difficulty.HARD },
    { "image": "🍍", "word": "pineapple", "sentence": "a sweet p__apple", "missing": "ine", "difficulty": Difficulty.HARD },
    { "image": "🥪", "word": "sandwich", "sentence": "eat a s__wich", "missing": "and", "difficulty": Difficulty.HARD },
    { "image": "🍫", "word": "chocolate", "sentence": "sweet ch__late", "missing": "oco", "difficulty": Difficulty.HARD },
    { "image": "🍦", "word": "ice cream", "sentence": "cold i__ cream", "missing": "ce", "difficulty": Difficulty.HARD },
    { "image": "🐊", "word": "crocodile", "sentence": "a green c__odile", "missing": "roc", "difficulty": Difficulty.HARD },
    { "image": "🦘", "word": "kangaroo", "sentence": "a jumping k__aroo", "missing": "ang", "difficulty": Difficulty.HARD },
    { "image": "🦛", "word": "hippo", "sentence": "a big h__po", "missing": "ip", "difficulty": Difficulty.HARD },
    { "image": "🦒", "word": "giraffe", "sentence": "a tall g__ffe", "missing": "ira", "difficulty": Difficulty.HARD },
    { "image": "🧑‍🚀", "word": "astronaut", "sentence": "fly like an a__naut", "missing": "stro", "difficulty": Difficulty.HARD },
    { "image": "🎆", "word": "fireworks", "sentence": "bright f__works", "missing": "ire", "difficulty": Difficulty.HARD },
    { "image": "🌂", "word": "umbrella", "sentence": "use an u__ella", "missing": "mbr", "difficulty": Difficulty.HARD }
];

export const ENGLISH_SENTENCES: EnglishSentence[] = [
    { "image": "☀️", "sentence": "The __ is bright.", "missing": "sun", "difficulty": Difficulty.EASY },
    { "image": "🐱", "sentence": "My __ is cute.", "missing": "cat", "difficulty": Difficulty.EASY },
    { "image": "🚗", "sentence": "I have a red __.", "missing": "car", "difficulty": Difficulty.EASY },
    { "image": "🍎", "sentence": "I like to eat an __.", "missing": "apple", "difficulty": Difficulty.EASY },
    { "image": "🥛", "sentence": "I drink __ every day.", "missing": "milk", "difficulty": Difficulty.EASY },
    { "image": "📖", "sentence": "She is reading a __.", "missing": "book", "difficulty": Difficulty.EASY },
    { "image": "🐶", "sentence": "The __ is barking.", "missing": "dog", "difficulty": Difficulty.EASY },
    { "image": "🛏️", "sentence": "Go to __ now.", "missing": "bed", "difficulty": Difficulty.EASY },
    { "image": "🐟", "sentence": "A __ can swim.", "missing": "fish", "difficulty": Difficulty.EASY },
    { "image": "🐷", "sentence": "The __ is pink.", "missing": "pig", "difficulty": Difficulty.EASY },
    { "image": "⚽️", "sentence": "Let's play __.", "missing": "ball", "difficulty": Difficulty.EASY },
    { "image": "✋", "sentence": "Wash your __.", "missing": "hand", "difficulty": Difficulty.EASY },
    { "image": "🐝", "sentence": "The __ is yellow.", "missing": "bee", "difficulty": Difficulty.EASY },
    { "image": "🥚", "sentence": "I want an __.", "missing": "egg", "difficulty": Difficulty.EASY },
    { "image": "👑", "sentence": "He is a __.", "missing": "king", "difficulty": Difficulty.EASY },
    { "image": "🧢", "sentence": "Put on your __.", "missing": "hat", "difficulty": Difficulty.EASY },
    { "image": "📦", "sentence": "Open the __.", "missing": "box", "difficulty": Difficulty.EASY },
    { "image": "🚌", "sentence": "Take the __ to school.", "missing": "bus", "difficulty": Difficulty.EASY },
    { "image": "🏃", "sentence": "I can __ fast.", "missing": "run", "difficulty": Difficulty.EASY },
    { "image": "🦵", "sentence": "I hurt my __.", "missing": "leg", "difficulty": Difficulty.EASY },
    { "image": "🛑", "sentence": "The color is __.", "missing": "red", "difficulty": Difficulty.EASY },
    { "image": "🌲", "sentence": "A big green __.", "missing": "tree", "difficulty": Difficulty.EASY },
    { "image": "🏫", "sentence": "They go to __ by bus.", "missing": "school", "difficulty": Difficulty.MEDIUM },
    { "image": "💧", "sentence": "Please drink more __.", "missing": "water", "difficulty": Difficulty.MEDIUM },
    { "image": "🌳", "sentence": "That __ is very tall.", "missing": "tree", "difficulty": Difficulty.MEDIUM },
    { "image": "🏠", "sentence": "We live in a big __.", "missing": "house", "difficulty": Difficulty.MEDIUM },
    { "image": "🍓", "sentence": "This __ is sweet.", "missing": "strawberry", "difficulty": Difficulty.MEDIUM },
    { "image": "🌙", "sentence": "The __ is beautiful tonight.", "missing": "moon", "difficulty": Difficulty.MEDIUM },
    { "image": "🐯", "sentence": "A __ can run fast.", "missing": "tiger", "difficulty": Difficulty.MEDIUM },
    { "image": "💡", "sentence": "Turn on the __, please.", "missing": "light", "difficulty": Difficulty.MEDIUM },
    { "image": "🌸", "sentence": "What a beautiful __!", "missing": "flower", "difficulty": Difficulty.MEDIUM },
    { "image": "🪑", "sentence": "Please sit on the __.", "missing": "chair", "difficulty": Difficulty.MEDIUM },
    { "image": "🚆", "sentence": "The __ is coming.", "missing": "train", "difficulty": Difficulty.MEDIUM },
    { "image": "🍞", "sentence": "I eat __ for breakfast.", "missing": "bread", "difficulty": Difficulty.MEDIUM },
    { "image": "🐑", "sentence": "The __ is white.", "missing": "sheep", "difficulty": Difficulty.MEDIUM },
    { "image": "⭐", "sentence": "Look at the __!", "missing": "star", "difficulty": Difficulty.MEDIUM },
    { "image": "😊", "sentence": "I feel __ today.", "missing": "happy", "difficulty": Difficulty.MEDIUM },
    { "image": "🍽️", "sentence": "Set the __ for dinner.", "missing": "table", "difficulty": Difficulty.MEDIUM },
    { "image": "🐎", "sentence": "The __ can gallop.", "missing": "horse", "difficulty": Difficulty.MEDIUM },
    { "image": "🐦", "sentence": "The __ can fly.", "missing": "bird", "difficulty": Difficulty.MEDIUM },
    { "image": "🍕", "sentence": "I love to eat __.", "missing": "pizza", "difficulty": Difficulty.MEDIUM },
    { "image": "🧀", "sentence": "Mice like __.", "missing": "cheese", "difficulty": Difficulty.MEDIUM },
    { "image": "👟", "sentence": "Tie your __.", "missing": "shoes", "difficulty": Difficulty.MEDIUM },
    { "image": "🦁", "sentence": "The __ is the king.", "missing": "lion", "difficulty": Difficulty.MEDIUM },
    { "image": "🏊", "sentence": "I like to __.", "missing": "swim", "difficulty": Difficulty.MEDIUM },
    { "image": "✈️", "sentence": "Look at the __.", "missing": "plane", "difficulty": Difficulty.MEDIUM },
    { "image": "👩‍⚕️", "sentence": "The __ helps sick people.", "missing": "doctor", "difficulty": Difficulty.MEDIUM },
    { "image": "👮", "sentence": "The __ keeps us safe.", "missing": "police", "difficulty": Difficulty.MEDIUM },
    { "image": "👩‍🏫", "sentence": "Listen to the __.", "missing": "teacher", "difficulty": Difficulty.MEDIUM },
    { "image": "🎸", "sentence": "He plays the __.", "missing": "guitar", "difficulty": Difficulty.MEDIUM },
    { "image": "🌍", "sentence": "We live on __.", "missing": "earth", "difficulty": Difficulty.MEDIUM },
    { "image": "🦋", "sentence": "A colorful __.", "missing": "butterfly", "difficulty": Difficulty.MEDIUM }
];

export const PRESCHOOL_ANIMALS: PreschoolItem[] = [
  { "id": "dog", "name": "Con Chó", "image": "🐶" },
  { "id": "cat", "name": "Con Mèo", "image": "🐱" },
  { "id": "mouse", "name": "Con Chuột", "image": "🐭" },
  { "id": "hamster", "name": "Chuột Hamster", "image": "🐹" },
  { "id": "rabbit", "name": "Con Thỏ", "image": "🐰" },
  { "id": "fox", "name": "Con Cáo", "image": "🦊" },
  { "id": "bear", "name": "Con Gấu", "image": "🐻" },
  { "id": "panda", "name": "Gấu Trúc", "image": "🐼" },
  { "id": "koala", "name": "Gấu Koala", "image": "🐨" },
  { "id": "tiger", "name": "Con Hổ", "image": "🐯" },
  { "id": "lion", "name": "Sư Tử", "image": "🦁" },
  { "id": "cow", "name": "Con Bò", "image": "🐮" },
  { "id": "pig", "name": "Con Heo", "image": "🐷" },
  { "id": "frog", "name": "Con Ếch", "image": "🐸" },
  { "id": "monkey", "name": "Con Khỉ", "image": "🐵" },
  { "id": "chicken", "name": "Con Gà", "image": "🐔" },
  { "id": "penguin", "name": "Chim Cánh Cụt", "image": "🐧" },
  { "id": "bird", "name": "Con Chim", "image": "🐦" },
  { "id": "duck", "name": "Con Vịt", "image": "🦆" },
  { "id": "eagle", "name": "Đại Bàng", "image": "🦅" },
  { "id": "owl", "name": "Con Cú", "image": "🦉" },
  { "id": "bat", "name": "Con Dơi", "image": "🦇" },
  { "id": "wolf", "name": "Chó Sói", "image": "🐺" },
  { "id": "horse", "name": "Con Ngựa", "image": "🐴" },
  { "id": "unicorn", "name": "Kỳ Lân", "image": "🦄" },
  { "id": "bee", "name": "Con Ong", "image": "🐝" },
  { "id": "butterfly", "name": "Con Bướm", "image": "🦋" },
  { "id": "snail", "name": "Ốc Sên", "image": "🐌" },
  { "id": "ladybug", "name": "Bọ Rùa", "image": "🐞" },
  { "id": "ant", "name": "Con Kiến", "image": "🐜" },
  { "id": "spider", "name": "Con Nhện", "image": "🕷️" },
  { "id": "fish", "name": "Con Cá", "image": "🐠" },
  { "id": "dolphin", "name": "Cá Heo", "image": "🐬" },
  { "id": "whale", "name": "Cá Voi", "image": "🐳" },
  { "id": "shark", "name": "Cá Mập", "image": "🦈" },
  { "id": "octopus", "name": "Bạch Tuộc", "image": "🐙" },
  { "id": "crab", "name": "Con Cua", "image": "🦀" },
  { "id": "turtle", "name": "Con Rùa", "image": "🐢" },
  { "id": "snake", "name": "Con Rắn", "image": "🐍" },
  { "id": "crocodile", "name": "Cá Sấu", "image": "🐊" }
];

export const PRESCHOOL_OBJECTS: PreschoolItem[] = [
  { "id": "ball", "name": "Quả Bóng", "image": "⚽️" },
  { "id": "apple", "name": "Quả Táo", "image": "🍎" },
  { "id": "star", "name": "Ngôi Sao", "image": "⭐" },
  { "id": "car", "name": "Cái Ô Tô", "image": "🚗" },
  { "id": "balloon", "name": "Bóng Bay", "image": "🎈" },
  { "id": "gift", "name": "Hộp Quà", "image": "🎁" },
  { "id": "flower", "name": "Bông Hoa", "image": "🌷" },
  { "id": "sun", "name": "Mặt Trời", "image": "🌞" },
  { "id": "diamond", "name": "Kim Cương", "image": "💎" },
  { "id": "burger", "name": "Bánh Burger", "image": "🍔" },
  { "id": "pizza", "name": "Bánh Pizza", "image": "🍕" },
  { "id": "strawberry", "name": "Quả Dâu Tây", "image": "🍓" },
  { "id": "watermelon", "name": "Dưa Hấu", "image": "🍉" },
  { "id": "pineapple", "name": "Quả Dứa", "image": "🍍" },
  { "id": "pants", "name": "Cái Quần", "image": "👖" },
  { "id": "shirt", "name": "Cái Áo", "image": "👕" },
  { "id": "dress", "name": "Cái Váy", "image": "👗" },
  { "id": "house", "name": "Ngôi Nhà", "image": "🏠" },
  { "id": "castle", "name": "Lâu Đài", "image": "🏰" },
  { "id": "airplane", "name": "Máy Bay", "image": "✈️" },
  { "id": "rocket", "name": "Tên Lửa", "image": "🚀" },
  { "id": "helicopter", "name": "Trực Thăng", "image": "🚁" },
  { "id": "guitar", "name": "Đàn Ghi-ta", "image": "🎸" },
  { "id": "piano", "name": "Đàn Piano", "image": "🎹" },
  { "id": "trumpet", "name": "Cái Kèn", "image": "🎺" },
  { "id": "drum", "name": "Cái Trống", "image": "🥁" },
  { "id": "phone", "name": "Điện Thoại", "image": "📱" },
  { "id": "laptop", "name": "Máy Tính Xách Tay", "image": "💻" },
  { "id": "watch", "name": "Đồng Hồ", "image": "⌚️" },
  { "id": "lightbulb", "name": "Bóng Đèn", "image": "💡" },
  { "id": "key", "name": "Chìa Khoá", "image": "🔑" },
  { "id": "lock", "name": "Ổ Khoá", "image": "🔒" },
  { "id": "book", "name": "Quyển Sách", "image": "📚" },
  { "id": "pencil", "name": "Bút Chì", "image": "✏️" },
  { "id": "crown", "name": "Vương Miện", "image": "👑" },
  { "id": "hat", "name": "Cái Mũ", "image": "🎩" },
  { "id": "umbrella", "name": "Cái Ô", "image": "☂️" },
  { "id": "rainbow", "name": "Cầu Vồng", "image": "🌈" }
];

export const PRESCHOOL_COLORS: PreschoolColor[] = [
  { "id": "red", "name": "Màu Đỏ", "hex": "#ef4444" },
  { "id": "blue", "name": "Màu Xanh Dương", "hex": "#3b82f6" },
  { "id": "green", "name": "Màu Xanh Lá", "hex": "#22c55e" },
  { "id": "yellow", "name": "Màu Vàng", "hex": "#eab308" },
  { "id": "orange", "name": "Màu Cam", "hex": "#f97316" },
  { "id": "purple", "name": "Màu Tím", "hex": "#a855f7" },
  { "id": "pink", "name": "Màu Hồng", "hex": "#ec4899" },
  { "id": "black", "name": "Màu Đen", "hex": "#1f2937" },
  { "id": "white", "name": "Màu Trắng", "hex": "#ffffff" },
  { "id": "brown", "name": "Màu Nâu", "hex": "#78350f" },
  { "id": "gray", "name": "Màu Xám", "hex": "#6b7280" }
];

export const PRESCHOOL_SHAPES: PreschoolShape[] = [
  { "id": "circle", "name": "Hình Tròn" },
  { "id": "square", "name": "Hình Vuông" },
  { "id": "triangle", "name": "Hình Tam Giác" },
  { "id": "star", "name": "Ngôi Sao" },
  { "id": "heart", "name": "Hình Trái Tim" }
];